In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#addition
c=a+b
#sub
d=a-b
#ele,ment multiplication
e=a*b
#matrix multiplication
g=a@b
#transpose
f=a.T
print("addition:",c)
print("sub:",d)
print("multiplication:",e)
print("matrix multi:",g)
print("transpose:",f)

addition: [[ 6  8]
 [10 12]]
sub: [[-4 -4]
 [-4 -4]]
multiplication: [[ 5 12]
 [21 32]]
matrix multi: [[19 22]
 [43 50]]
transpose: [[1 3]
 [2 4]]


In [2]:
import numpy as np
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Perform SVD
U,S,VT = np.linalg.svd(X)
n_components=2
#matrix with reduced dimensions

X_reconstructed = np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
